%% Build CCCV Charging Simulink Model
% Generates a fully-wired discrete simulation model.
% Structure: CCCV Controller -> PWM Comparator -> Battery Discrete Plant

function build_cccv_model()

model_name = 'cccv_charging_sim';

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
new_system(model_name);
open_system(model_name);

%% Simulation parameters (all discrete)
set_param(model_name, 'StopTime', '200');
set_param(model_name, 'Solver', 'FixedStepDiscrete');
set_param(model_name, 'FixedStep', '1e-4');

%% ===== Top-level blocks =====
add_block('simulink/Ports & Subsystems/Subsystem', ...
    [model_name '/CCCV_Controller'], 'Position', [90 80 320 220]);

add_block('simulink/Sources/Repeating Sequence', ...
    [model_name '/Carrier'], 'Position', [380 270 500 320]);
set_param([model_name '/Carrier'], ...
    'rep_seq_t', '[0 5e-5 1e-4]', ...
    'rep_seq_y', '[0 1 0]');

add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [model_name '/PWM_Compare'], 'Position', [550 200 630 260]);
set_param([model_name '/PWM_Compare'], 'Operator', '>');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model_name '/PWM_to_Double'], 'Position', [670 210 770 250]);
set_param([model_name '/PWM_to_Double'], 'OutDataTypeStr', 'double');

add_block('simulink/Ports & Subsystems/Subsystem', ...
    [model_name '/Battery_Plant'], 'Position', [830 80 1080 260]);

add_block('simulink/Sinks/Scope', [model_name '/Scope_Duty'], ...
    'Position', [830 300 930 350]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_I_batt'], ...
    'Position', [1120 90 1220 140]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_V_batt'], ...
    'Position', [1120 170 1220 220]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_SOC'], ...
    'Position', [1120 250 1220 300]);

%% ===== CCCV Controller Subsystem =====
ctrl = [model_name '/CCCV_Controller'];
try
    delete_line(ctrl, 'In1/1', 'Out1/1');
catch
end

add_block('simulink/Ports & Subsystems/In1', [ctrl '/I_batt'], ...
    'Position', [30 130 60 150]);

set_param([ctrl '/In1'], 'Name', 'V_batt');
set_param([ctrl '/Out1'], 'Name', 'Duty_cmd');

add_block('simulink/Sources/Constant', [ctrl '/I_ref_CC'], ...
    'Position', [30 20 100 50]);
set_param([ctrl '/I_ref_CC'], 'Value', '50');

add_block('simulink/Sources/Constant', [ctrl '/V_ref_CV'], ...
    'Position', [30 70 100 100]);
set_param([ctrl '/V_ref_CV'], 'Value', '420');

add_block('simulink/Math Operations/Sum', [ctrl '/Sum_V'], ...
    'Position', [140 70 160 100]);
set_param([ctrl '/Sum_V'], 'Inputs', '+-');

add_block('simulink/Discrete/Discrete PID Controller', [ctrl '/PI_Voltage'], ...
    'Position', [200 62 320 108]);
set_param([ctrl '/PI_Voltage'], ...
    'P', '1.0', ...
    'I', '15', ...
    'D', '0', ...
    'InitialConditionForIntegrator', '0', ...
    'SampleTime', '1e-4', ...
    'LimitOutput', 'on', ...
    'UpperSaturationLimit', '50', ...
    'LowerSaturationLimit', '0');

add_block('simulink/Math Operations/MinMax', [ctrl '/Min_CCCV'], ...
    'Position', [360 30 430 100]);
set_param([ctrl '/Min_CCCV'], 'Function', 'min', 'Inputs', '2');

add_block('simulink/Math Operations/Sum', [ctrl '/Sum_I'], ...
    'Position', [470 20 490 50]);
set_param([ctrl '/Sum_I'], 'Inputs', '+-');

add_block('simulink/Discrete/Discrete PID Controller', [ctrl '/PI_Current'], ...
    'Position', [530 12 650 58]);
set_param([ctrl '/PI_Current'], ...
    'P', '0.03', ...
    'I', '5', ...
    'D', '0', ...
    'InitialConditionForIntegrator', '0', ...
    'SampleTime', '1e-4', ...
    'LimitOutput', 'on', ...
    'UpperSaturationLimit', '0.95', ...
    'LowerSaturationLimit', '0');

add_line(ctrl, 'V_ref_CV/1', 'Sum_V/1', 'autorouting', 'on');
add_line(ctrl, 'V_batt/1', 'Sum_V/2', 'autorouting', 'on');
add_line(ctrl, 'Sum_V/1', 'PI_Voltage/1', 'autorouting', 'on');
add_line(ctrl, 'I_ref_CC/1', 'Min_CCCV/1', 'autorouting', 'on');
add_line(ctrl, 'PI_Voltage/1', 'Min_CCCV/2', 'autorouting', 'on');
add_line(ctrl, 'Min_CCCV/1', 'Sum_I/1', 'autorouting', 'on');
add_line(ctrl, 'I_batt/1', 'Sum_I/2', 'autorouting', 'on');
add_line(ctrl, 'Sum_I/1', 'PI_Current/1', 'autorouting', 'on');
add_line(ctrl, 'PI_Current/1', 'Duty_cmd/1', 'autorouting', 'on');

%% ===== Battery Plant Subsystem =====
plant = [model_name '/Battery_Plant'];
try
    delete_line(plant, 'In1/1', 'Out1/1');
catch
end

delete_block([plant '/Out1']);

set_param([plant '/In1'], 'Name', 'Duty_pwm');

add_block('simulink/Ports & Subsystems/Out1', [plant '/V_batt'], ...
    'Position', [400 55 430 75]);
add_block('simulink/Ports & Subsystems/Out1', [plant '/I_batt'], ...
    'Position', [400 115 430 135]);
add_block('simulink/Ports & Subsystems/Out1', [plant '/SOC'], ...
    'Position', [400 175 430 195]);

add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [plant '/PlantCore'], 'Position', [130 70 340 205]);
set_param([plant '/PlantCore'], 'Script', plant_core_script());

add_line(plant, 'Duty_pwm/1', 'PlantCore/1', 'autorouting', 'on');
add_line(plant, 'PlantCore/1', 'V_batt/1', 'autorouting', 'on');
add_line(plant, 'PlantCore/2', 'I_batt/1', 'autorouting', 'on');
add_line(plant, 'PlantCore/3', 'SOC/1', 'autorouting', 'on');

%% ===== Top-level wiring =====
add_line(model_name, 'CCCV_Controller/1', 'PWM_Compare/1', 'autorouting', 'on');
add_line(model_name, 'Carrier/1', 'PWM_Compare/2', 'autorouting', 'on');
add_line(model_name, 'PWM_Compare/1', 'PWM_to_Double/1', 'autorouting', 'on');
add_line(model_name, 'PWM_to_Double/1', 'Battery_Plant/1', 'autorouting', 'on');

add_line(model_name, 'Battery_Plant/1', 'CCCV_Controller/1', 'autorouting', 'on');
add_line(model_name, 'Battery_Plant/2', 'CCCV_Controller/2', 'autorouting', 'on');

add_line(model_name, 'CCCV_Controller/1', 'Scope_Duty/1', 'autorouting', 'on');
add_line(model_name, 'Battery_Plant/1', 'Scope_V_batt/1', 'autorouting', 'on');
add_line(model_name, 'Battery_Plant/2', 'Scope_I_batt/1', 'autorouting', 'on');
add_line(model_name, 'Battery_Plant/3', 'Scope_SOC/1', 'autorouting', 'on');

%% Save model
save_system(model_name);
fprintf('CCCV simulation model "%s" created (fully wired).\n', model_name);
fprintf('Control parameters: Icc=50A, Vcv=420V, Ts=1e-4s\n');

end

function code = plant_core_script()
code = [...
"function [V_batt, I_batt, SOC] = fcn(Duty_pwm)" newline ...
"%#codegen" newline ...
"persistent soc" newline ...
"if isempty(soc)" newline ...
"    soc = 0.20;" newline ...
"end" newline ...
"Ts = 1e-4;" newline ...
"Vbus = 750;" newline ...
"Rint = 0.08;" newline ...
"CapAh = 100;" newline ...
"Duty = min(max(Duty_pwm,0),0.95);" newline ...
"Voc = (3.0 + 1.2*soc) * 100;" newline ...
"I_raw = (Duty * Vbus - Voc) / Rint;" newline ...
"I_batt = min(max(I_raw,0),80);" newline ...
"soc = soc + I_batt * Ts / (CapAh * 3600);" newline ...
"soc = min(max(soc,0),1);" newline ...
"SOC = soc;" newline ...
"V_batt = Voc + I_batt * Rint;" newline ...
"end" ...
];
end
