%% Multi-Mode Island Load Testbed
% Supports: Base RL load, Step load switching, Nonlinear rectifier,
% and optional inductive transient response testing.

function populate_island_load_advanced(model_name)
% Creates an advanced island load subsystem with selectable operating modes

sys = [model_name '/Island_Load'];

% Clean existing subsystem
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

% Inputs: [Vabc, LoadMode]
% LoadMode: 1=Base RL, 2=Base RL + Step, 3=Rectifier nonlinear, 4=Inductive motor
add_block('simulink/Ports & Subsystems/In1', [sys '/Vabc_in'], 'Position', [30 40 60 60]);
add_block('simulink/Ports & Subsystems/In1', [sys '/LoadMode'], 'Position', [30 100 60 120]);

% Output: [Iload_abc]
add_block('simulink/Ports & Subsystems/Out1', [sys '/Iload'], 'Position', [500 70 530 90]);

% ===== Load Unit 1: Base RL Load (always active) =====
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Base_RL_Load'], ...
    'Position', [120 30 280 80]);
set_ml_fcn_adv(sys, 'Base_RL_Load', [...
    'function I_base = fcn(Vabc)' newline ...
    '%#codegen' newline ...
    'persistent iL' newline ...
    'if isempty(iL), iL = zeros(3,1); end' newline ...
    'Ts = 1e-4; R_base = 10; L_base = 5e-3;' newline ...
    'diL = (Vabc - R_base*iL) / L_base;' newline ...
    'iL = iL + diL * Ts;' newline ...
    'I_base = iL;' newline ...
    'end']);

% ===== Load Unit 2: Step Load (switches in at t=0.15s) =====
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Step_Load'], ...
    'Position', [120 110 280 160]);
set_ml_fcn_adv(sys, 'Step_Load', [...
    'function I_step = fcn(Vabc, mode)' newline ...
    '%#codegen' newline ...
    'persistent iL2 t_start t_enable' newline ...
    'if isempty(iL2), iL2 = zeros(3,1); t_start=0; t_enable=false; end' newline ...
    'Ts = 1e-4; R_step = 15; L_step = 3e-3;' newline ...
    'if mode >= 2 && ~t_enable' newline ...
    '    t_enable = true; t_start = 0;' newline ...
    'end' newline ...
    'if t_enable' newline ...
    '    t_start = t_start + Ts;' newline ...
    '    if t_start > 0.15' newline ...
    '        diL2 = (Vabc - R_step*iL2) / L_step;' newline ...
    '        iL2 = iL2 + diL2 * Ts;' newline ...
    '    end' newline ...
    'end' newline ...
    'I_step = iL2;' newline ...
    'end']);

% ===== Load Unit 3: Nonlinear Rectifier Load (three-phase diode bridge) =====
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Rectifier_Load'], ...
    'Position', [120 190 280 240]);
set_ml_fcn_adv(sys, 'Rectifier_Load', [...
    'function I_rect = fcn(Vabc, mode)' newline ...
    '%#codegen' newline ...
    'persistent iL3 Vdc_cap t' newline ...
    'if isempty(iL3), iL3 = zeros(3,1); Vdc_cap = 450; t = 0; end' newline ...
    'Ts = 1e-4;' newline ...
    'if mode >= 3' newline ...
    '    L_in = 2e-3; R_in = 0.5; C_load = 1000e-6; R_load = 20;' newline ...
    '    %% Diode bridge rectification (simplified nonlinear model)' newline ...
    '    V_max = max(abs(Vabc));' newline ...
    '    %% Diode forward drop' newline ...
    '    Vf = 0.7;' newline ...
    '    %% Average DC voltage with diode drops' newline ...
    '    Vdc_meas = 3*sqrt(2)/pi * V_max - 2*Vf;' newline ...
    '    %% AC-side current (nonlinear, contains low-order harmonics)' newline ...
    '    for k = 1:3' newline ...
    '        diL = (Vabc(k) - R_in*iL3(k)) / L_in;' newline ...
    '        iL3(k) = iL3(k) + diL * Ts;' newline ...
    '        %% Diode clipping: current only flows when voltage exceeds DC cap' newline ...
    '        if Vabc(k) < Vdc_cap - Vf, iL3(k) = 0; end' newline ...
    '    end' newline ...
    '    %% DC-side capacitor charging' newline ...
    '    I_dc_avg = (Vabc(1)*iL3(1) + Vabc(2)*iL3(2) + Vabc(3)*iL3(3)) / Vdc_meas;' newline ...
    '    dV_cap = (I_dc_avg - Vdc_cap/R_load) / C_load;' newline ...
    '    Vdc_cap = Vdc_cap + dV_cap * Ts;' newline ...
    '    Vdc_cap = max(Vdc_cap, 300);' newline ...
    '    I_rect = iL3;' newline ...
    'else' newline ...
    '    I_rect = zeros(3,1);' newline ...
    'end' newline ...
    'end']);

% ===== Load Unit 4: Motor Inductive Load (RL with back-EMF effect) =====
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Motor_Load'], ...
    'Position', [120 270 280 320]);
set_ml_fcn_adv(sys, 'Motor_Load', [...
    'function I_motor = fcn(Vabc, mode)' newline ...
    '%#codegen' newline ...
    'persistent iL4 w_motor' newline ...
    'if isempty(iL4), iL4 = zeros(3,1); w_motor = 0; end' newline ...
    'Ts = 1e-4;' newline ...
    'if mode >= 4' newline ...
    '    R_motor = 5; L_motor = 8e-3; J = 0.01; Ke = 0.5;' newline ...
    '    Tm = 10; Bm = 0.5;' newline ...
    '    %% Induction motor simplified (single-phase representation)' newline ...
    '    ia = Vabc(1);' newline ...
    '    e_back = Ke * w_motor;' newline ...
    '    di = (ia - e_back - R_motor*iL4(1)) / L_motor;' newline ...
    '    iL4(1) = iL4(1) + di * Ts;' newline ...
    '    %% Torque and speed update' newline ...
    '    Te = Ke * iL4(1);' newline ...
    '    dw = (Te - Tm - Bm*w_motor) / J;' newline ...
    '    w_motor = w_motor + dw * Ts;' newline ...
    '    w_motor = max(w_motor, 0);' newline ...
    '    I_motor = iL4;' newline ...
    'else' newline ...
    '    I_motor = zeros(3,1);' newline ...
    'end' newline ...
    'end']);

% ===== Load Combiner (sum all active loads based on mode) =====
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Load_Selector'], ...
    'Position', [320 100 480 200]);
set_ml_fcn_adv(sys, 'Load_Selector', [...
    'function I_total = fcn(I_base, I_step, I_rect, I_motor)' newline ...
    '%#codegen' newline ...
    '%% Sum all load components (all active simultaneously)' newline ...
    'I_total = I_base + I_step + I_rect + I_motor;' newline ...
    'end']);

% ===== Wiring =====
add_line(sys, 'Vabc_in/1', 'Base_RL_Load/1', 'autorouting', 'on');
add_line(sys, 'Vabc_in/1', 'Step_Load/1', 'autorouting', 'on');
add_line(sys, 'LoadMode/1', 'Step_Load/2', 'autorouting', 'on');
add_line(sys, 'Vabc_in/1', 'Rectifier_Load/1', 'autorouting', 'on');
add_line(sys, 'LoadMode/1', 'Rectifier_Load/2', 'autorouting', 'on');
add_line(sys, 'Vabc_in/1', 'Motor_Load/1', 'autorouting', 'on');
add_line(sys, 'LoadMode/1', 'Motor_Load/2', 'autorouting', 'on');

add_line(sys, 'Base_RL_Load/1', 'Load_Selector/1', 'autorouting', 'on');
add_line(sys, 'Step_Load/1', 'Load_Selector/2', 'autorouting', 'on');
add_line(sys, 'Rectifier_Load/1', 'Load_Selector/3', 'autorouting', 'on');
add_line(sys, 'Motor_Load/1', 'Load_Selector/4', 'autorouting', 'on');

add_line(sys, 'Load_Selector/1', 'Iload/1', 'autorouting', 'on');

end

%% Helper to set MATLAB Function script
function set_ml_fcn_adv(sys, block_name, code)
blk_path = [sys '/' block_name];
sf = sfroot();
chart = find(sf, '-isa', 'Stateflow.EMChart', 'Path', blk_path);
if ~isempty(chart)
    chart.Script = code;
end
end
