function build_integrated_system_model()
% Build a fully populated integrated PCS Simulink model for R2024b.
% Each subsystem contains functional MATLAB Function blocks implementing
% the actual control/plant algorithms rather than empty placeholders.

model_name = 'integrated_energy_system';
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
new_system(model_name);
open_system(model_name);

%% Simulation parameters
set_param(model_name, 'StopTime', '0.5');
set_param(model_name, 'Solver', 'FixedStepDiscrete');
set_param(model_name, 'FixedStep', '1e-4');
set_param(model_name, 'SimulationMode', 'normal');

%% ===== Top-level blocks =====
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/Grid_Source'], ...
    'Position', [50 140 160 200]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/PCC_Breaker'], ...
    'Position', [210 130 320 210]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/LCL_Filter'], ...
    'Position', [370 130 480 210]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/AFE_3Level'], ...
    'Position', [530 120 680 220]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/DC_Bus'], ...
    'Position', [730 110 860 230]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/BiDir_DCDC'], ...
    'Position', [910 80 1060 180]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/Battery_Pack'], ...
    'Position', [1110 90 1220 170]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/DCAC_Inverter'], ...
    'Position', [910 260 1060 360]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/Island_Load'], ...
    'Position', [1110 270 1220 350]);
add_block('simulink/Ports & Subsystems/Subsystem', [model_name '/Controller'], ...
    'Position', [370 380 860 580]);
add_block('simulink/Discrete/Unit Delay', [model_name '/DCDC_Duty_Z1'], ...
    'Position', [885 145 915 175]);
set_param([model_name '/DCDC_Duty_Z1'], 'SampleTime', '1e-4', 'InitialCondition', '0');

% Scopes
add_block('simulink/Sinks/Scope', [model_name '/Scope_Vdc'], 'Position', [920 350 980 380]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_Iabc'], 'Position', [920 390 980 420]);
add_block('simulink/Sinks/Scope', [model_name '/Scope_Batt'], 'Position', [1150 190 1210 220]);

%% ===== Populate all subsystems =====
populate_grid_source(model_name);
populate_pcc_breaker(model_name);
populate_lcl_filter(model_name);
populate_afe(model_name);
populate_dc_bus(model_name);
populate_dcdc(model_name);
populate_battery(model_name);
populate_inverter(model_name);
populate_island_load(model_name);
populate_controller(model_name);

%% ===== Top-level wiring =====
% Power path: Grid -> PCC -> LCL -> AFE -> DC_Bus
add_line(model_name, 'Grid_Source/1', 'PCC_Breaker/1', 'autorouting', 'on');
add_line(model_name, 'PCC_Breaker/1', 'LCL_Filter/1', 'autorouting', 'on');
add_line(model_name, 'LCL_Filter/1', 'AFE_3Level/1', 'autorouting', 'on');
add_line(model_name, 'AFE_3Level/1', 'DC_Bus/1', 'autorouting', 'on');
% DC_Bus -> DCDC -> Battery
add_line(model_name, 'DC_Bus/1', 'BiDir_DCDC/1', 'autorouting', 'on');
add_line(model_name, 'BiDir_DCDC/1', 'Battery_Pack/1', 'autorouting', 'on');
% DC_Bus -> Inverter -> Load
add_line(model_name, 'DC_Bus/1', 'DCAC_Inverter/1', 'autorouting', 'on');
add_line(model_name, 'DCAC_Inverter/1', 'Island_Load/1', 'autorouting', 'on');

% Measurement feedback to controller
add_line(model_name, 'Grid_Source/1', 'Controller/1', 'autorouting', 'on');
add_line(model_name, 'LCL_Filter/2', 'Controller/2', 'autorouting', 'on');
add_line(model_name, 'DC_Bus/2', 'Controller/3', 'autorouting', 'on');
add_line(model_name, 'Battery_Pack/1', 'Controller/4', 'autorouting', 'on');

% Controller commands to actuators
add_line(model_name, 'Controller/1', 'PCC_Breaker/2', 'autorouting', 'on');
add_line(model_name, 'Controller/2', 'AFE_3Level/2', 'autorouting', 'on');
add_line(model_name, 'Controller/3', 'DCDC_Duty_Z1/1', 'autorouting', 'on');
add_line(model_name, 'DCDC_Duty_Z1/1', 'BiDir_DCDC/2', 'autorouting', 'on');
add_line(model_name, 'Controller/4', 'DCAC_Inverter/2', 'autorouting', 'on');

% Scope connections
add_line(model_name, 'DC_Bus/2', 'Scope_Vdc/1', 'autorouting', 'on');
add_line(model_name, 'LCL_Filter/2', 'Scope_Iabc/1', 'autorouting', 'on');
add_line(model_name, 'Battery_Pack/1', 'Scope_Batt/1', 'autorouting', 'on');

%% Save
save_system(model_name);
fprintf('Integrated PCS model "%s" built with populated subsystems.\n', model_name);
end

%% ========== Subsystem population functions ==========

function populate_grid_source(model_name)
sys = [model_name '/Grid_Source'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
set_param([sys '/Out1'], 'Name', 'Vabc', 'Position', [300 40 330 60]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/GridGen'], ...
    'Position', [80 30 230 80]);
set_ml_fcn(sys, 'GridGen', [...
    'function Vabc = fcn()' newline ...
    '%#codegen' newline ...
    'persistent t' newline ...
    'if isempty(t), t = 0; end' newline ...
    'Ts = 1e-4; f = 50; Vm = 311;' newline ...
    'w = 2*pi*f;' newline ...
    'va = Vm*cos(w*t);' newline ...
    'vb = Vm*cos(w*t - 2*pi/3);' newline ...
    'vc = Vm*cos(w*t + 2*pi/3);' newline ...
    'Vabc = [va; vb; vc];' newline ...
    't = t + Ts;' newline ...
    'end']);
add_line(sys, 'GridGen/1', 'Vabc/1', 'autorouting', 'on');
end

function populate_pcc_breaker(model_name)
sys = [model_name '/PCC_Breaker'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Vabc_in'], 'Position', [30 40 60 60]);
add_block('simulink/Ports & Subsystems/In1', [sys '/PCC_cmd'], 'Position', [30 100 60 120]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Vabc_out'], 'Position', [300 55 330 75]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Breaker'], ...
    'Position', [120 40 250 120]);
set_ml_fcn(sys, 'Breaker', [...
    'function Vout = fcn(Vin, cmd)' newline ...
    '%#codegen' newline ...
    '% PCC breaker: passes voltage when cmd >= 0.5' newline ...
    'if cmd >= 0.5' newline ...
    '    Vout = Vin;' newline ...
    'else' newline ...
    '    Vout = zeros(size(Vin));' newline ...
    'end' newline ...
    'end']);
add_line(sys, 'Vabc_in/1', 'Breaker/1', 'autorouting', 'on');
add_line(sys, 'PCC_cmd/1', 'Breaker/2', 'autorouting', 'on');
add_line(sys, 'Breaker/1', 'Vabc_out/1', 'autorouting', 'on');
end

function populate_lcl_filter(model_name)
sys = [model_name '/LCL_Filter'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Vin'], 'Position', [30 40 60 60]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Vout'], 'Position', [380 40 410 60]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Iabc'], 'Position', [380 90 410 110]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/LCL'], ...
    'Position', [120 30 320 110]);
set_ml_fcn(sys, 'LCL', [...
    'function [Vout, Iabc] = fcn(Vin)' newline ...
    '%#codegen' newline ...
    'persistent iL vC' newline ...
    'if isempty(iL), iL = zeros(3,1); vC = zeros(3,1); end' newline ...
    'Ts = 1e-4; L1 = 3e-3; R1 = 0.1; Cf = 10e-6;' newline ...
    'diL = (Vin - R1*iL - vC) / L1;' newline ...
    'iL = iL + diL * Ts;' newline ...
    'dvC = iL / Cf;' newline ...
    'vC = vC + dvC * Ts;' newline ...
    'Vout = vC;' newline ...
    'Iabc = iL;' newline ...
    'end']);
add_line(sys, 'Vin/1', 'LCL/1', 'autorouting', 'on');
add_line(sys, 'LCL/1', 'Vout/1', 'autorouting', 'on');
add_line(sys, 'LCL/2', 'Iabc/1', 'autorouting', 'on');
end

function populate_afe(model_name)
sys = [model_name '/AFE_3Level'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Vabc'], 'Position', [30 30 60 50]);
add_block('simulink/Ports & Subsystems/In1', [sys '/PWM'], 'Position', [30 80 60 100]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Idc'], 'Position', [380 50 410 70]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/AFE_Avg'], ...
    'Position', [120 30 320 100]);
set_ml_fcn(sys, 'AFE_Avg', [...
    'function Idc = fcn(Vabc, PWM)' newline ...
    '%#codegen' newline ...
    '% Average-value model of 3-phase PWM rectifier' newline ...
    '% Idc = sum(duty_k * i_k), i_k from grid voltage / Zeq' newline ...
    'persistent iL' newline ...
    'if isempty(iL), iL = zeros(3,1); end' newline ...
    'Ts = 1e-4; Lac = 5e-3; Rac = 0.1; Vdc_est = 750;' newline ...
    'D = min(max(PWM, 0.05), 0.95);' newline ...
    'Vconv = (D - 0.5) * Vdc_est;' newline ...
    'diL = (Vabc - Vconv - Rac*iL) / Lac;' newline ...
    'iL = iL + diL * Ts;' newline ...
    'Idc = sum(D .* iL);' newline ...
    'end']);
add_line(sys, 'Vabc/1', 'AFE_Avg/1', 'autorouting', 'on');
add_line(sys, 'PWM/1', 'AFE_Avg/2', 'autorouting', 'on');
add_line(sys, 'AFE_Avg/1', 'Idc/1', 'autorouting', 'on');
end

function populate_dc_bus(model_name)
sys = [model_name '/DC_Bus'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Idc_in'], 'Position', [30 40 60 60]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Vdc'], 'Position', [380 40 410 60]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Meas'], 'Position', [380 90 410 110]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/CapModel'], ...
    'Position', [120 30 320 110]);
set_ml_fcn(sys, 'CapModel', [...
    'function [Vdc, Meas] = fcn(Idc_in)' newline ...
    '%#codegen' newline ...
    'persistent vc1 vc2' newline ...
    'if isempty(vc1), vc1 = 375; vc2 = 375; end' newline ...
    'Ts = 1e-4; C1 = 4700e-6; C2 = 4700e-6;' newline ...
    '% Split bus capacitor with midpoint' newline ...
    'vc1 = vc1 + (Idc_in * 0.5) * Ts / C1;' newline ...
    'vc2 = vc2 + (Idc_in * 0.5) * Ts / C2;' newline ...
    'Vdc = vc1 + vc2;' newline ...
    'Meas = [Vdc; vc1; vc2];' newline ...
    'end']);
add_line(sys, 'Idc_in/1', 'CapModel/1', 'autorouting', 'on');
add_line(sys, 'CapModel/1', 'Vdc/1', 'autorouting', 'on');
add_line(sys, 'CapModel/2', 'Meas/1', 'autorouting', 'on');
end

function populate_dcdc(model_name)
sys = [model_name '/BiDir_DCDC'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Vdc_in'], 'Position', [30 30 60 50]);
add_block('simulink/Ports & Subsystems/In1', [sys '/Duty'], 'Position', [30 80 60 100]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Ibatt'], 'Position', [380 50 410 70]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/DCDC_Avg'], ...
    'Position', [120 30 320 100]);
set_ml_fcn(sys, 'DCDC_Avg', [...
    'function Ibatt = fcn(Vdc_in, Duty)' newline ...
    '%#codegen' newline ...
    'persistent iL' newline ...
    'if isempty(iL), iL = 0; end' newline ...
    'Ts = 1e-4; L = 1e-3; R = 0.01; Vbatt_nom = 360;' newline ...
    'D = min(max(Duty, 0), 0.95);' newline ...
    'diL = (D * Vdc_in - Vbatt_nom - R*iL) / L;' newline ...
    'iL = iL + diL * Ts;' newline ...
    'iL = min(max(iL, -80), 80);' newline ...
    'Ibatt = iL;' newline ...
    'end']);
add_line(sys, 'Vdc_in/1', 'DCDC_Avg/1', 'autorouting', 'on');
add_line(sys, 'Duty/1', 'DCDC_Avg/2', 'autorouting', 'on');
add_line(sys, 'DCDC_Avg/1', 'Ibatt/1', 'autorouting', 'on');
end

function populate_battery(model_name)
sys = [model_name '/Battery_Pack'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Ibatt_in'], 'Position', [30 40 60 60]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/BattMeas'], 'Position', [380 40 410 60]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/BattModel'], ...
    'Position', [120 30 320 80]);
set_ml_fcn(sys, 'BattModel', [...
    'function BattMeas = fcn(Ibatt)' newline ...
    '%#codegen' newline ...
    'persistent soc' newline ...
    'if isempty(soc), soc = 0.3; end' newline ...
    'Ts = 1e-4; CapAh = 100; Ncells = 100; Rint = 0.001;' newline ...
    'soc = soc + Ibatt * Ts / (CapAh * 3600);' newline ...
    'soc = min(max(soc, 0), 1);' newline ...
    'Voc_cell = 3.0 + 1.2*soc;' newline ...
    'Vbatt = Ncells * (Voc_cell + Ibatt * Rint);' newline ...
    'BattMeas = [Vbatt; Ibatt; soc];' newline ...
    'end']);
add_line(sys, 'Ibatt_in/1', 'BattModel/1', 'autorouting', 'on');
add_line(sys, 'BattModel/1', 'BattMeas/1', 'autorouting', 'on');
end

function populate_inverter(model_name)
sys = [model_name '/DCAC_Inverter'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Vdc_in'], 'Position', [30 30 60 50]);
add_block('simulink/Ports & Subsystems/In1', [sys '/PWM'], 'Position', [30 80 60 100]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Vout'], 'Position', [380 50 410 70]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/INV_Avg'], ...
    'Position', [120 30 320 100]);
set_ml_fcn(sys, 'INV_Avg', [...
    'function Vout = fcn(Vdc, PWM)' newline ...
    '%#codegen' newline ...
    '% Averaged inverter: Vout = (duty - 0.5) * Vdc' newline ...
    'D = min(max(PWM, 0.05), 0.95);' newline ...
    'Vout = (D - 0.5) * Vdc;' newline ...
    'end']);
add_line(sys, 'Vdc_in/1', 'INV_Avg/1', 'autorouting', 'on');
add_line(sys, 'PWM/1', 'INV_Avg/2', 'autorouting', 'on');
add_line(sys, 'INV_Avg/1', 'Vout/1', 'autorouting', 'on');
end

function populate_island_load(model_name)
sys = [model_name '/Island_Load'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys '/Vabc_in'], 'Position', [30 40 60 60]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/Iload'], 'Position', [500 80 530 100]);

%% Base RL Load (always active)
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/RL_Base'], ...
    'Position', [120 20 280 70]);
set_ml_fcn(sys, 'RL_Base', [...
    'function I_base = fcn(Vabc)' newline ...
    '%#codegen' newline ...
    'persistent iL' newline ...
    'if isempty(iL), iL = zeros(3,1); end' newline ...
    'Ts = 1e-4; R = 10; L = 5e-3;' newline ...
    'diL = (Vabc - R*iL) / L;' newline ...
    'iL = iL + diL * Ts;' newline ...
    'I_base = iL;' newline ...
    'end']);

%% Step Load (adds load step at t=0.15s)
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/RL_Step'], ...
    'Position', [120 90 280 140]);
set_ml_fcn(sys, 'RL_Step', [...
    'function I_step = fcn(Vabc)' newline ...
    '%#codegen' newline ...
    'persistent iL t_elapsed' newline ...
    'if isempty(iL), iL = zeros(3,1); t_elapsed = 0; end' newline ...
    'Ts = 1e-4; R_step = 15; L_step = 3e-3;' newline ...
    't_elapsed = t_elapsed + Ts;' newline ...
    '% Step in at t=0.15s, magnitude = 0.5 x Ibase' newline ...
    'if t_elapsed >= 0.15' newline ...
    '    diL = (Vabc - R_step*iL) / L_step;' newline ...
    '    iL = iL + diL * Ts;' newline ...
    'else' newline ...
    '    iL = zeros(3,1);' newline ...
    'end' newline ...
    'I_step = iL;' newline ...
    'end']);

%% Nonlinear Rectifier Load (3-phase bridge + DC side)
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/Rectifier'], ...
    'Position', [120 160 280 220]);
set_ml_fcn(sys, 'Rectifier', [...
    'function I_rect = fcn(Vabc)' newline ...
    '%#codegen' newline ...
    'persistent iL3 vdc_cap' newline ...
    'if isempty(iL3), iL3 = zeros(3,1); vdc_cap = 450; end' newline ...
    'Ts = 1e-4; L_in = 2e-3; R_in = 0.5; C_dc = 1000e-6; R_load = 20;' newline ...
    'Vf = 0.7; Vdc_thresh = 400;' newline ...
    '%% AC-side inductor (simplified rectifier input)' newline ...
    'for k = 1:3' newline ...
    '    diL = (Vabc(k) - R_in*iL3(k)) / L_in;' newline ...
    '    iL3(k) = iL3(k) + diL * Ts;' newline ...
    '    % Diode clipping: only conduct when AC > DC' newline ...
    '    if abs(Vabc(k)) < (vdc_cap - Vf)' newline ...
    '        iL3(k) = max(iL3(k), 0);' newline ...
    '    end' newline ...
    'end' newline ...
    '%% DC-side capacitor model' newline ...
    'I_dc_avg = mean(abs(iL3));' newline ...
    'dvdc = (I_dc_avg - vdc_cap/R_load) * Ts / C_dc;' newline ...
    'vdc_cap = vdc_cap + dvdc;' newline ...
    'vdc_cap = min(max(vdc_cap, 300), 650);' newline ...
    'I_rect = iL3;' newline ...
    'end']);

%% Load Summers (combines base + step + rectifier)
add_block('simulink/Ports & Subsystems/Subsystem', [sys '/Combiner'], ...
    'Position', [320 60 480 200]);
sys_comb = [sys '/Combiner'];
try delete_block([sys_comb '/In1']); catch, end
try delete_block([sys_comb '/Out1']); catch, end

add_block('simulink/Ports & Subsystems/In1', [sys_comb '/I_base_in'], 'Position', [20 20 50 40]);
add_block('simulink/Ports & Subsystems/In1', [sys_comb '/I_step_in'], 'Position', [20 60 50 80]);
add_block('simulink/Ports & Subsystems/In1', [sys_comb '/I_rect_in'], 'Position', [20 100 50 120]);
add_block('simulink/Ports & Subsystems/Out1', [sys_comb '/I_total'], 'Position', [150 60 180 80]);

%% Sum block
add_block('simulink/Math Operations/Sum', [sys_comb '/Add3'], 'Position', [80 40 110 100], ...
    'Inputs', '+++');
add_line(sys_comb, 'I_base_in/1', 'Add3/1', 'autorouting', 'on');
add_line(sys_comb, 'I_step_in/1', 'Add3/2', 'autorouting', 'on');
add_line(sys_comb, 'I_rect_in/1', 'Add3/3', 'autorouting', 'on');
add_line(sys_comb, 'Add3/1', 'I_total/1', 'autorouting', 'on');

%% Top-level connections
add_line(sys, 'Vabc_in/1', 'RL_Base/1', 'autorouting', 'on');
add_line(sys, 'Vabc_in/1', 'RL_Step/1', 'autorouting', 'on');
add_line(sys, 'Vabc_in/1', 'Rectifier/1', 'autorouting', 'on');

add_line(sys, 'RL_Base/1', 'Combiner/1', 'autorouting', 'on');
add_line(sys, 'RL_Step/1', 'Combiner/2', 'autorouting', 'on');
add_line(sys, 'Rectifier/1', 'Combiner/3', 'autorouting', 'on');

add_line(sys, 'Combiner/1', 'Iload/1', 'autorouting', 'on');
end

function populate_controller(model_name)
sys = [model_name '/Controller'];
try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
try delete_block([sys '/In1']); catch, end
try delete_block([sys '/Out1']); catch, end

% Inputs
add_block('simulink/Ports & Subsystems/In1', [sys '/Vgrid'], 'Position', [30 30 60 50]);
add_block('simulink/Ports & Subsystems/In1', [sys '/Igrid'], 'Position', [30 80 60 100]);
add_block('simulink/Ports & Subsystems/In1', [sys '/DC_Meas'], 'Position', [30 130 60 150]);
add_block('simulink/Ports & Subsystems/In1', [sys '/Batt_Meas'], 'Position', [30 180 60 200]);

% Outputs
add_block('simulink/Ports & Subsystems/Out1', [sys '/PCC_cmd'], 'Position', [650 30 680 50]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/AFE_PWM'], 'Position', [650 80 680 100]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/DCDC_duty'], 'Position', [650 130 680 150]);
add_block('simulink/Ports & Subsystems/Out1', [sys '/INV_PWM'], 'Position', [650 180 680 200]);

% PLL
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/PLL'], ...
    'Position', [120 20 240 60]);
set_ml_fcn(sys, 'PLL', [...
    'function theta = fcn(Vabc)' newline ...
    '%#codegen' newline ...
    'persistent th integ' newline ...
    'if isempty(th), th = 0; integ = 0; end' newline ...
    'Ts = 1e-4; Kp = 100; Ki = 5000; w0 = 2*pi*50;' newline ...
    'va = Vabc(1); vb = Vabc(2); vc = Vabc(3);' newline ...
    'v_alpha = 2/3*(va - 0.5*vb - 0.5*vc);' newline ...
    'v_beta = 2/3*(sqrt(3)/2*vb - sqrt(3)/2*vc);' newline ...
    'vq = -v_alpha*sin(th) + v_beta*cos(th);' newline ...
    'integ = integ + Ki*vq*Ts;' newline ...
    'w_est = Kp*vq + integ + w0;' newline ...
    'th = th + w_est*Ts;' newline ...
    'th = mod(th, 2*pi);' newline ...
    'theta = th;' newline ...
    'end']);

% GFL current controller
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/GFL_Ctrl'], ...
    'Position', [320 20 500 85]);
set_ml_fcn(sys, 'GFL_Ctrl', [...
    'function PWM = fcn(Iabc, theta)' newline ...
    '%#codegen' newline ...
    'persistent int_d int_q' newline ...
    'if isempty(int_d), int_d = 0; int_q = 0; end' newline ...
    'Ts = 1e-4; Kp = 10; Ki = 100; Lf = 3e-3; Vdc = 750;' newline ...
    'w = 2*pi*50;' newline ...
    'ia = Iabc(1); ib = Iabc(2); ic = Iabc(3);' newline ...
    'i_al = 2/3*(ia-0.5*ib-0.5*ic);' newline ...
    'i_be = 2/3*(sqrt(3)/2*ib - sqrt(3)/2*ic);' newline ...
    'id = i_al*cos(theta) + i_be*sin(theta);' newline ...
    'iq = -i_al*sin(theta) + i_be*cos(theta);' newline ...
    'id_ref = 10; iq_ref = 0;' newline ...
    'err_d = id_ref - id; err_q = iq_ref - iq;' newline ...
    'int_d = int_d + Ki*err_d*Ts;' newline ...
    'int_q = int_q + Ki*err_q*Ts;' newline ...
    'int_d = min(max(int_d,-300),300);' newline ...
    'int_q = min(max(int_q,-300),300);' newline ...
    'vd = Kp*err_d + int_d - w*Lf*iq;' newline ...
    'vq = Kp*err_q + int_q + w*Lf*id;' newline ...
    'v_al = vd*cos(theta) - vq*sin(theta);' newline ...
    'v_be = vd*sin(theta) + vq*cos(theta);' newline ...
    'da = 0.5 + v_al/Vdc;' newline ...
    'db = 0.5 + (-0.5*v_al + sqrt(3)/2*v_be)/Vdc;' newline ...
    'dc = 0.5 + (-0.5*v_al - sqrt(3)/2*v_be)/Vdc;' newline ...
    'PWM = [min(max(da,0.05),0.95);' newline ...
    '       min(max(db,0.05),0.95);' newline ...
    '       min(max(dc,0.05),0.95)];' newline ...
    'end']);

% Islanding detection -> PCC command
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/IslandDet'], ...
    'Position', [120 100 240 145]);
set_ml_fcn(sys, 'IslandDet', [...
    'function pcc_cmd = fcn(Vabc)' newline ...
    '%#codegen' newline ...
    'persistent tmr' newline ...
    'if isempty(tmr), tmr = 0; end' newline ...
    'Ts = 1e-4; Vnom = 311; V_hi = 1.1; V_lo = 0.88; t_trip = 2.0;' newline ...
    'Vpk = max(abs(Vabc));' newline ...
    'V_pu = Vpk / Vnom;' newline ...
    'if V_pu > V_hi || V_pu < V_lo' newline ...
    '    tmr = tmr + Ts;' newline ...
    'else' newline ...
    '    tmr = 0;' newline ...
    'end' newline ...
    'if tmr >= t_trip' newline ...
    '    pcc_cmd = 0;' newline ...
    'else' newline ...
    '    pcc_cmd = 1;' newline ...
    'end' newline ...
    'end']);

% CCCV mode manager -> DCDC duty
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/CCCV_Ctrl'], ...
    'Position', [320 120 500 170]);
set_ml_fcn(sys, 'CCCV_Ctrl', [...
    'function duty = fcn(BattMeas)' newline ...
    '%#codegen' newline ...
    'persistent int_i int_v' newline ...
    'if isempty(int_i), int_i = 0; int_v = 0; end' newline ...
    'Ts = 1e-4; Icc = 50; Vcv = 420;' newline ...
    'Kp_i = 0.03; Ki_i = 5; Kp_v = 1; Ki_v = 15;' newline ...
    'Vbatt = BattMeas(1); Ibatt = BattMeas(2);' newline ...
    '% CV loop' newline ...
    'err_v = Vcv - Vbatt;' newline ...
    'int_v = int_v + Ki_v*err_v*Ts;' newline ...
    'int_v = min(max(int_v, 0), Icc);' newline ...
    'Iref_cv = Kp_v*err_v + int_v;' newline ...
    'Iref_cv = min(max(Iref_cv, 0), Icc);' newline ...
    '% CC/CV min selector' newline ...
    'Iref = min(Icc, Iref_cv);' newline ...
    '% Current loop' newline ...
    'err_i = Iref - Ibatt;' newline ...
    'int_i = int_i + Ki_i*err_i*Ts;' newline ...
    'int_i = min(max(int_i, 0), 0.95);' newline ...
    'duty = Kp_i*err_i + int_i;' newline ...
    'duty = min(max(duty, 0), 0.95);' newline ...
    'end']);

% GFM VSG/Droop -> Inverter PWM
add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/GFM_VSG'], ...
    'Position', [320 180 500 230]);
set_ml_fcn(sys, 'GFM_VSG', [...
    'function PWM = fcn(DC_Meas)' newline ...
    '%#codegen' newline ...
    'persistent th w_vsg' newline ...
    'if isempty(th), th = 0; w_vsg = 2*pi*50; end' newline ...
    'Ts = 1e-4; J = 0.5; D = 50; w0 = 2*pi*50; E = 311;' newline ...
    'Vdc = DC_Meas(1);' newline ...
    'if Vdc < 1, Vdc = 750; end' newline ...
    'Pref = 0; Pmeas = 0;' newline ...
    'Tm = Pref/w0; Te = Pmeas/max(w_vsg,1);' newline ...
    'dw = (Tm - Te - D*(w_vsg-w0))/J;' newline ...
    'w_vsg = w_vsg + dw*Ts;' newline ...
    'w_vsg = min(max(w_vsg, 2*pi*48), 2*pi*52);' newline ...
    'th = mod(th + w_vsg*Ts, 2*pi);' newline ...
    'va = E*cos(th); vb = E*cos(th-2*pi/3); vc = E*cos(th+2*pi/3);' newline ...
    'da = 0.5+va/Vdc; db = 0.5+vb/Vdc; dc = 0.5+vc/Vdc;' newline ...
    'PWM = [min(max(da,0.05),0.95);' newline ...
    '       min(max(db,0.05),0.95);' newline ...
    '       min(max(dc,0.05),0.95)];' newline ...
    'end']);

% Internal wiring
add_line(sys, 'Vgrid/1', 'PLL/1', 'autorouting', 'on');
add_line(sys, 'Igrid/1', 'GFL_Ctrl/1', 'autorouting', 'on');
add_line(sys, 'PLL/1', 'GFL_Ctrl/2', 'autorouting', 'on');
add_line(sys, 'Vgrid/1', 'IslandDet/1', 'autorouting', 'on');
add_line(sys, 'Batt_Meas/1', 'CCCV_Ctrl/1', 'autorouting', 'on');
add_line(sys, 'DC_Meas/1', 'GFM_VSG/1', 'autorouting', 'on');

add_line(sys, 'IslandDet/1', 'PCC_cmd/1', 'autorouting', 'on');
add_line(sys, 'GFL_Ctrl/1', 'AFE_PWM/1', 'autorouting', 'on');
add_line(sys, 'CCCV_Ctrl/1', 'DCDC_duty/1', 'autorouting', 'on');
add_line(sys, 'GFM_VSG/1', 'INV_PWM/1', 'autorouting', 'on');
end

%% ===== MATLAB Function script setter (R2024b compatible) =====
function set_ml_fcn(sys, block_name, code)
% Set the script of a MATLAB Function block via Stateflow API.
% This works in R2024b.
blk_path = [sys '/' block_name];
sf = sfroot();
chart = find(sf, '-isa', 'Stateflow.EMChart', 'Path', blk_path);
if ~isempty(chart)
    chart.Script = code;
end
end
